name: api1
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

jobs:
  terraform_refresh_only_job:
    runs-on: ubuntu-latest
    steps:
    - id: terraform
      run: |
        write-host ${{ github.event.inputs.json }}
      shell: pwsh 